server:
  port: 80
spring:
  application:
    name: service-consumer #Eureka上的服务名字
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka  #EurekaServer地址
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms

feign:
  hystrix:
    enabled: true
