server:
  port: 10087
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000